# Generated by Django 3.1.3 on 2021-04-20 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='name',
            new_name='emotion',
        ),
        migrations.DeleteModel(
            name='Emotion',
        ),
    ]
